### PR TITLE
Install package with latest updates

### PR DESCRIPTION
**Pull request by fawazahmed0**
Ref: https://github.com/ssut/py-googletrans/issues/152

### CODE REVIEW

**Comment by ssut** [comment]
Because this is not a stable way that can encourage people to use possibly broken master, it may lead to a broken code. I think it's good enough to make people to track the issues till I release the next version. Sorry for this.

**Comment by soumendrak** [comment]
@ssut, Could you please let us know, when are you planning to release the next version?

**Comment by ssut** [comment]
@soumendrak it's coming up very soon: #181.

**Comment by fawazahmed0** [comment]
@ssut Thanks for releasing the new version

**Pull request closed without merging**
