### PR TITLE
Adding default service_urls list issue#165

### PR DESCRIPTION
**Pull request by terryyz**
[https://github.com/ssut/py-googletrans/issues/165](url)

### CODE REVIEW

**Comment by ssut** [comment]
Could you describe purpose of this? I think it would be a good idea to put this in constants if you just wanted to show possible service urls.

**Comment by terryyz** [comment]
Yes, this is for showing available service urls we can use. User can choose one of them they like. I've put the list in the constant. Do you mean it would be better if I set `def __init__(self, service_urls=None, user_agent=DEFAULT_USER_AGENT,
                 proxies=None, timeout=None):
                 proxies=None, timeout=None, available_service_list=DEFAULT_SERVICE_URLS)` ?

**Comment by ssut** [comment]
@terryyz It seems `self.available_service_list` is not referenced from the Client's methods so I think it does not need to have that property (available_service_list) in Client, storing in constants is enough.

**Comment by terryyz** [comment]
Okay. I will close this and pull another request.

**Pull request closed without merging**
