### PR TITLE
Adding default service_urls

### PR DESCRIPTION
**Pull request by terryyz**
https://github.com/ssut/py-googletrans/issues/165

### CODE REVIEW

**Comment by ssut** [comment]
I'm sorry for giving you one more thing: I think it would be better to use tuple instead because list type is mutable by default.

**Comment by terryyz** [comment]
Sure, let me have it changed.

**Comment by ssut** [comment]
I merged down to master, and also this will be in the release 3.0. Thanks!

**Comment by terryyz** [comment]
I'll try to continue working on this repo and manage it as well if possible :p

**Pull request merged**
