### PR TITLE
release: v4.0.0

### PR DESCRIPTION
**Pull request by ssut**
This PR introduces the long-awaited v4.0.0 release of py-googletrans. After years of feedback and community contributions, this update brings significant changes to improve stability, usability, and maintainability over v3.

## Highlights

- Resolved Most Reported Issues: addresses and resolves longstanding problems.
- Async-only API: Transitioned to a modern asynchronous API to improve scalability and better align with current Python development practices.
- Complete Type Annotations: Introduced full type hints to make the library easier to use with modern IDEs.
- Modernized Codebase: Refactored the entire codebase for maintainability and to follow modern de-facto Python standards.

## Breaking Changes

- API Transition to Async: All synchronous APIs have been removed. If you’re upgrading, ensure your code is updated to use async functions.

---

Expected release date: 2024 Dec

### CODE REVIEW

**Comment by StephanAkkerman** [comment]
@ssut When can we expect a new pypi release?

**Comment by ssut** [comment]
I am currently experiencing issues publishing the v4.0.0 release using uv. I expect to resolve this within a week or by this weekend.

**Comment by ssut** [comment]
> @ssut When can we expect a new pypi release?

I am currently experiencing issues publishing the v4.0.0 release using uv. I expect to resolve this within a week or by this weekend.

**Comment by ssut** [comment]
I've just published the release to PyPI: https://pypi.org/project/googletrans/4.0.1/

**Pull request merged**
